language: python

python:
  - "2.7"

env:
 - VERSION="7.0" ODOO_REPO="odoo/odoo"
 - VERSION="7.0" ODOO_REPO="OCA/OCB"
 - VERSION="7.0" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install libxml2-dev
  - sudo apt-get install libxslt1-dev

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/account-closing.git -b 7.0 ${HOME}/account-closing
  - git clone https://github.com/hbrunn/web.git -b 7.0-web_relativedelta_squashed ${HOME}/web
  - git clone https://github.com/mcassuto/CP-modules-for-travis.git -b 7.0 ${HOME}/CP-modules-for-travis
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
